dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - aave/protocol-v2@1.0.1
compiler:
  evm_version: null
  solc:
    version: "0.8.0"
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@aave=aave/protocol-v2@1.0.1"
dotenv: .env
networks:
  default: mainnet-fork-new
